% FUNCTION
% Compute_L_Hill.m
%__________________________________________________________________________
%
% PURPOSE
% Computation of the generalised muscle lever arms
%
% SYNOPSIS
% (Segment,Model) = Compute_L_Hill(Segment,Model)
%
% INPUT
% Segment (cf. data structure in user guide)
% Model (cf. data structure in user guide)
%
% OUTPUT
% Segment (cf. data structure in user guide)
% Model (cf. data structure in user guide)
%
% DESCRIPTION
% Definition of the virtuels markers for origin, via and insertion of
% muscles and computation of the lever arms
%
% REFERENCES
%__________________________________________________________________________
%
% CALLED FUNCTIONS (FROM MUSCULO-SKELETAL TOOLBOX)
% Mprod_array3.m
% Vnorm_array3.m
%
% MATLAB VERSION
% Matlab R2020a
%__________________________________________________________________________
%
% CHANGELOG
% Created by Raphaël Dumas, Florent Moissent, Edouard Jouan
% September 2012
%
% Modified by Raphael Dumas
% March 2020
% Generic vs. Informed structures (Segment, Joint, Model)
% n,f,fc as Model.Informed fields
%__________________________________________________________________________


function [Segment,Model] = Compute_L_Hill(Segment,Model)

% Number of frames
n = Model.Informed.n;


%% -------------------------------------------------------------------------
% Scaling and interpolation matrices
% -------------------------------------------------------------------------

% Segment 2
i = 2;
% Muscles scaled by a homothety of centre at proximal endpoint
for j = 4:15
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = inv(Segment(i).Informed.B) * ...
        Segment(i).Generic.rVs(:,j)*Segment(i).Informed.Scale;
end

% Segment 3
i = 3;
% Muscles scaled by a homothety of centre at proximal endpoint
for j = 10:19
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = inv(Segment(i).Informed.B) * ...
        Segment(i).Generic.rVs(:,j)*Segment(i).Informed.Scale;
end
% Muscles scaled by a homothety of centre at distal endpoint
% Tibialis posterior
% tibialis anterior
% Peroneus brevis
% Peroneus longus
% Peroneus tertius
% Extensor digitorum longus
% Extensor hallucis longus
% Flexor digitorum longus
% Flexor hallucis longus
for j = 20:28
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = [0; -1; 0] + inv(Segment(i).Informed.B) * ...
        (Segment(i).Generic.rVs(:,j) + [0; Segment(i).Generic.L; 0])*...
        Segment(i).Informed.Scale;
end

% Segment 4
i = 4;
% Muscles scaled by a homothety of centre at proximal endpoint
for j = 2:5
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = inv(Segment(i).Informed.B) * ...
        Segment(i).Generic.rVs(:,j)*Segment(i).Informed.Scale;
end

% Segment 5
i = 5;
% Muscles scaled by a homothety of centre at proximal endpoint
for j = [7:19,21:27,30,32,35,37]
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = inv(Segment(i).Informed.B) * ...
        Segment(i).Generic.rVs(:,j)*Segment(i).Informed.Scale;
end
% Muscles scaled by a homothety of centre at distal endpoint
% Adductor magnus III
% Tensor fasciae latae
% Sartorius
% Rectus femoris (from -83.65 to -150 degrees of knee flexion)
% Vastus medialis (from -69.32 to -101.99 degrees of knee flexion)
% Vastus medialis (from -101.99 to -150 of knee flexion)
% Vastus intermedialis (from -81.36 to -150 degrees of knee flexion)
% Vastus lateralis (from -69.32 to -110 degrees of knee flexion
% Vastus lateralis (considered as origin from -110 to -150 degrees of knee flexion)
% Gastrocnemius medialis (from 5.73 to -44.12 degrees of knee flexion)
% Gastrocnemius medialis (from -44.12 to -150 degrees of knee flexion)
% Gastrocnemius lateralis (from 5.73 to -44.12 degrees of knee flexion)
% Gastrocnemius lateralis (from -44.12 to -150 degrees of knee flexion)
for j = [20,28,29,31,34,34,36,38:43]
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = [0; -1; 0] + inv(Segment(i).Informed.B) * ...
        (Segment(i).Generic.rVs(:,j) + [0; Segment(i).Generic.L; 0])*...
        Segment(i).Informed.Scale;
end

% Segment 6
i = 6;
% Muscles scaled by a homothety of centre at hip joint centre
for j = 2:28
    % Coordinates of virtual markers in Segment i
    % Expressed in (ui, rPi-rDi, wi)
    Segment(i).Informed.nV(:,j) = Segment(i).Informed.nV(:,1) + ...
        inv(Segment(i).Informed.B) * ...
        (Segment(i).Generic.rVs(:,j) + ...
        - Segment(i).Generic.rVs(:,1))*...
        Segment(i).Informed.Scale;
end

% Other muscle parameters and interpolation matrices
for i = 2:6 % From i = 2 (Foot) to i = 6 (Pelvis)
    
    % Muscle parameters
    Model.Informed.Lcst(:,i) = Model.Generic.Lcst(:,i)*Segment(i).Informed.Scale; 
    
    switch i
        case 2
            indj = 4:15; % Virtual markers start at 4 (others are for ankle joint)
        case 3
            indj = 10:28; % Virtual markers start at 10 (others are for ankle, tibio-femoral and patello-femoral joints)
        case 4
            indj = 2:5; % Virtual markers start at 2 (other is for patello-femoral joint)
        case 5
            indj = 7:43; % Virtual markers start at 7 (others are for tibio-femoral joint)
        case 6
            indj = 2:28; % Virtual markers start at 2 (other is for hip joint)
    end
    
    for j = indj
        % Interpolation matrix
        eval(['NV',num2str(j),num2str(i),...
            '= [Segment(',num2str(i),').Informed.nV(1,',num2str(j),')*eye(3),',...
            '(1 + Segment(',num2str(i),').Informed.nV(2,',num2str(j),'))*eye(3),',...
            '- Segment(',num2str(i),').Informed.nV(2,',num2str(j),')*eye(3),',...
            'Segment(',num2str(i),').Informed.nV(3,',num2str(j),')*eye(3)];']);
    end

end

% Muscle parameters
Model.Informed.L0(:,1) = Model.Generic.L0(:,1)*Model.Informed.Scale;
Model.Informed.Lts(:,1) = Model.Generic.Lts(:,1)*Model.Informed.Scale;
for j = 1:43
    Model.Informed.V0max(j,1) = 10*Model.Informed.L0(j,1);
end
Model.Informed.Fmax = Model.Generic.Fmax; % No scaling
Model.Informed.PCSA = Model.Generic.PCSA; % No scaling
Model.Informed.pennation = Model.Generic.pennation; % No scaling


%% -------------------------------------------------------------------------
% Generalised lever arms
% -------------------------------------------------------------------------

% Initialisation
Model.Informed.Lever = zeros(48,43,n);

% Gluteus maximus I
Model.Informed.Lever(:,1,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV75',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV26,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV75,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus maximus II
Model.Informed.Lever(:,2,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV85',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV36,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV85,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus maximus III
Model.Informed.Lever(:,3,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV95',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV46,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV95,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus medius I
Model.Informed.Lever(:,4,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV105',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV56,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV105,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus medius II
Model.Informed.Lever(:,5,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV115',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV66,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV115,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus medius III
Model.Informed.Lever(:,6,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV125',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV76,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV125,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus minimus I
Model.Informed.Lever(:,7,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV135',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV86,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV135,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus minimus II
Model.Informed.Lever(:,8,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV145',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV96,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV145,[1,1,n]),Segment(5).Informed.Q)))];

% Gluteus minimus III
Model.Informed.Lever(:,9,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV155',[1,1,n]),....
    Vnorm_array3(Mprod_array3(repmat(NV106,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV155,[1,1,n]),Segment(5).Informed.Q)))];

% Adductor longus
Model.Informed.Lever(:,10,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV165',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV116,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV165,[1,1,n]),Segment(5).Informed.Q)))];

% Adductor brevis
Model.Informed.Lever(:,11,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV175',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV126,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV175,[1,1,n]),Segment(5).Informed.Q)))];

% Adductor magnus I
Model.Informed.Lever(:,12,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV185',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV136,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV185,[1,1,n]),Segment(5).Informed.Q)))];

% Adductor magnus II
Model.Informed.Lever(:,13,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV195',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV146,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV195,[1,1,n]),Segment(5).Informed.Q)))];

% Adductor magnus III
Model.Informed.Lever(:,14,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV205',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV156,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV205,[1,1,n]),Segment(5).Informed.Q)))];

% Pectineus
Model.Informed.Lever(:,15,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV215',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV166,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV215,[1,1,n]),Segment(5).Informed.Q)))];

% Illiacus
Model.Informed.Lever(:,16,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV225',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV176,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV225,[1,1,n]),Segment(5).Informed.Q)))];

% Psoas
Model.Informed.Lever(:,17,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV235',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV186,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV235,[1,1,n]),Segment(5).Informed.Q)))];

% Quadratus femoris
Model.Informed.Lever(:,18,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV245',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV196,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV245,[1,1,n]),Segment(5).Informed.Q)))];

% Gemellus
Model.Informed.Lever(:,19,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV255',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV206,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV255,[1,1,n]),Segment(5).Informed.Q)))];

% Piriformis
Model.Informed.Lever(:,20,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV265',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV216,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV265,[1,1,n]),Segment(5).Informed.Q)))];

% Tensor fasciae latae
Model.Informed.Lever(:,21,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV103',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV285,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV103,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV275',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV226,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV275,[1,1,n]),Segment(5).Informed.Q))) ...
    - Mprod_array3(repmat(NV285',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV285,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV103,[1,1,n]),Segment(3).Informed.Q)))];

% Gracilis
Model.Informed.Lever(:,22,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV113',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV236,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV113,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Sartorius
Model.Informed.Lever(:,23,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV153',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV295,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV153,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV295',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV276,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV295,[1,1,n]),Segment(5).Informed.Q))) ...
    - Mprod_array3(repmat(NV295',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV295,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV153,[1,1,n]),Segment(3).Informed.Q)))];

% Semimenbranosus
Model.Informed.Lever(:,24,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV123',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV246,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV123,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Semitendinosus
Model.Informed.Lever(:,25,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV133',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV256,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV133,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Biceps femoris long head
Model.Informed.Lever(:,26,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV143',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV266,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV143,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Biceps femoris short head
Model.Informed.Lever(:,27,1:n) = [zeros(12,1,n);...
    Mprod_array3(repmat(NV163',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV305,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV163,[1,1,n]),Segment(3).Informed.Q)));...
    zeros(12,1,n);...
    - Mprod_array3(repmat(NV305',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV305,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV163,[1,1,n]),Segment(3).Informed.Q)))];

% Rectus femoris
Model.Informed.Lever(:,28,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV24',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV286,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV24,[1,1,n]),Segment(4).Informed.Q)));...
    zeros(12,1,n)];
% % Moving point in case of tibio-femoral angle < - 83.65 degrees
% ind = find(FE3 < -83.65);
% if ~isempty(ind)
%     display(['Using via point V315 for rectus femoris at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,28,ind) = [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV24',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV315,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV24,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         Mprod_array3(repmat(NV315',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV286,[1,1,ni]),Segment(6).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV315,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)))) ...
%         - Mprod_array3(repmat(NV315',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV315,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV24,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end

% Vastus medialis
% Using V325 as virtual marker for origin
Model.Informed.Lever(:,29,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV34',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV325,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV34,[1,1,n]),Segment(4).Informed.Q)));...
    - Mprod_array3(repmat(NV325',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV325,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV34,[1,1,n]),Segment(4).Informed.Q)))];
% % Using V335 as virtual marker for origin
% ind = find(FE3 < -69.32 & FE3 > -101.99);
% if ~isempty(ind)
%     display(['Using origin V335 for vastus medialis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,29,ind) =  [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV34',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         - Mprod_array3(repmat(NV335',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end
% % Using V345 as virtual marker for origin
% ind = find(FE3 < -101.99);
% if ~isempty(ind)
%     display(['Using origin V345 for vastus medialis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,29,ind) = [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV34',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV345,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         - Mprod_array3(repmat(NV345',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV345,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end

% Vastus intermedialis
% Using V355 as virtual marker for origin
Model.Informed.Lever(:,30,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV44',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV355,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV44,[1,1,n]),Segment(4).Informed.Q)));...
    - Mprod_array3(repmat(NV355',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV355,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV44,[1,1,n]),Segment(4).Informed.Q)))];
% % Using V365 as virtual marker for origin
% ind = find(FE3 < -81.36);
% if ~isempty(ind)
%     display(['Using origin V365 for vastus intermedialis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,30,ind) = [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV44',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV365,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV44,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         - Mprod_array3(repmat(NV365',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV365,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV44,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end

% Vastus lateralis
% Using V375 as virtual marker for origin
Model.Informed.Lever(:,31,1:n) = [zeros(12,1,n);...
    zeros(12,1,n);...
    Mprod_array3(repmat(NV54',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV375,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV54,[1,1,n]),Segment(4).Informed.Q)));...
    - Mprod_array3(repmat(NV375',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV375,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV54,[1,1,n]),Segment(4).Informed.Q)))];
% % Using V385 as virtual marker for origin
% ind = find(FE3 < -69.32 & FE3 > -110);
% if ~isempty(ind)
%     display(['Using origin V385 for vastus lateralis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,31,ind) = [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV54',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV385,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         - Mprod_array3(repmat(NV385',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV385,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end
% % Using V395 as virtual marker for origin
% ind = find(FE3 < -110);
% if ~isempty(ind)
%     display(['Using origin V395 for vastus lateralis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,31,ind) = [zeros(12,1,ni);...
%         zeros(12,1,ni);...
%         Mprod_array3(repmat(NV54',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV395,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))));...
%         - Mprod_array3(repmat(NV395',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV395,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))))];
% end

% Gastrocnemius medialis
% Using V405 as virtual marker for via point in the thigh
Model.Informed.Lever(:,32,1:n) = [Mprod_array3(repmat(NV42',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV42,[1,1,n]),Segment(2).Informed.Q)));...
    Mprod_array3(repmat(NV173',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV405,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q)) ...
    - Vnorm_array3(Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV42,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    - Mprod_array3(repmat(NV405',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV405,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q)))];
% % Using V415 as virtual marker for via point in the thigh
% ind = find(FE3 < -44.12);
% if ~isempty(ind)
%     display(['Using origin V415 for gastrocnemius medialis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,32,ind) = [Mprod_array3(repmat(NV42',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV42,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))));...
%         Mprod_array3(repmat(NV173',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV415,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)))...
%         - Vnorm_array3(Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV42,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))));...
%         zeros(12,1,ni);...
%         - Mprod_array3(repmat(NV415',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV415,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind))))];
% end

% Gastrocnemius lateralis
% Using V425 as virtual marker for via point in the thigh
Model.Informed.Lever(:,33,1:n) = [Mprod_array3(repmat(NV52',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV52,[1,1,n]),Segment(2).Informed.Q)));...
    Mprod_array3(repmat(NV183',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV425,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q)) ...
    - Vnorm_array3(Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV52,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    - Mprod_array3(repmat(NV425',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV425,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q)))];
% % Using V435 as virtual marker for via point in the thigh
% ind = find(FE3 < -44.12);
% if ~isempty(ind)
%     display(['Using origin V435 for gastrocnemius lateralis at frames ',num2str(ind')])
%     ni = size(ind,1);
%     Model.Informed.Lever(:,33,ind) = [Mprod_array3(repmat(NV52',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV52,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))));...
%         Mprod_array3(repmat(NV183',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV435,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind))) ...
%         - Vnorm_array3(Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV52,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))));...
%         zeros(12,1,ni);...
%         - Mprod_array3(repmat(NV435',[1,1,ni]),...
%         Vnorm_array3(Mprod_array3(repmat(NV435,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind))))];
% end

% Soleus
Model.Informed.Lever(:,34,1:n) = [Mprod_array3(repmat(NV62',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV193,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV62,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV193',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV193,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV62,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Tibialis posterior
Model.Informed.Lever(:,35,1:n) = [Mprod_array3(repmat(NV72',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV203,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV72,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV203',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV203,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV72,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Tibialis anterior
Model.Informed.Lever(:,36,1:n) = [Mprod_array3(repmat(NV82',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV213,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV82,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV213',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV213,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV82,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Peroneus brevis
Model.Informed.Lever(:,37,1:n) = [Mprod_array3(repmat(NV92',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV223,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV92,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV223',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV223,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV92,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Peroneus longus
Model.Informed.Lever(:,38,1:n) = [Mprod_array3(repmat(NV102',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV233,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV102,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV233',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV233,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV102,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Peroneus tertius
Model.Informed.Lever(:,39,1:n) = [Mprod_array3(repmat(NV112',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV243,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV112,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV243',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV243,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV112,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Extensor digitorum longus
Model.Informed.Lever(:,40,1:n) = [Mprod_array3(repmat(NV122',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV253,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV122,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV253',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV253,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV122,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Extensor hallucis longus
Model.Informed.Lever(:,41,1:n) = [Mprod_array3(repmat(NV132',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV263,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV132,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV263',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV263,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV132,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Flexor digitorum longus
Model.Informed.Lever(:,42,1:n) = [Mprod_array3(repmat(NV142',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV273,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV142,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV273',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV273,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV142,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];

% Flexor hallucis longus
Model.Informed.Lever(:,43,1:n) = [Mprod_array3(repmat(NV152',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV283,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV152,[1,1,n]),Segment(2).Informed.Q)));...
    - Mprod_array3(repmat(NV283',[1,1,n]),...
    Vnorm_array3(Mprod_array3(repmat(NV283,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV152,[1,1,n]),Segment(2).Informed.Q)));...
    zeros(12,1,n);...
    zeros(12,1,n)];


% -------------------------------------------------------------------------
% Musculo-tendon unit length
% -------------------------------------------------------------------------
% Initialisation
Model.Informed.Lmt = zeros(43,1,n);

% Gluteus maximus I
Model.Informed.Lmt(1,1,1:n) = repmat(sum(Model.Informed.Lcst(1,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV26,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV75,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus maximus II
Model.Informed.Lmt(2,1,1:n) = repmat(sum(Model.Informed.Lcst(2,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV36,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV85,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus maximus III
Model.Informed.Lmt(3,1,1:n) = repmat(sum(Model.Informed.Lcst(3,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV46,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV95,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus medius I
Model.Informed.Lmt(4,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(4,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV56,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV105,[1,1,n]),Segment(5).Informed.Q)).^2));


% Gluteus medius II
Model.Informed.Lmt(5,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(5,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV66,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV115,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus medius III
Model.Informed.Lmt(6,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(6,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV76,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV125,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus minimus I
Model.Informed.Lmt(7,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(7,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV86,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV135,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus minimus II
Model.Informed.Lmt(8,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(8,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV96,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV145,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gluteus minimus III
Model.Informed.Lmt(9,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(9,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV106,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV155,[1,1,n]),Segment(5).Informed.Q)).^2));

% Adductus longus
Model.Informed.Lmt(10,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(10,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV116,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV165,[1,1,n]),Segment(5).Informed.Q)).^2));

% Adductus brevis
Model.Informed.Lmt(11,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(11,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV126,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV175,[1,1,n]),Segment(5).Informed.Q)).^2));

% Adductus magnus I
Model.Informed.Lmt(12,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(12,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV136,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV185,[1,1,n]),Segment(5).Informed.Q)).^2));

% Adductus magnus II
Model.Informed.Lmt(13,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(13,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV146,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV195,[1,1,n]),Segment(5).Informed.Q)).^2));

% Adductus magnus III
Model.Informed.Lmt(14,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(14,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV156,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV205,[1,1,n]),Segment(5).Informed.Q)).^2));

% Pectineus
Model.Informed.Lmt(15,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(15,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV166,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV215,[1,1,n]),Segment(5).Informed.Q)).^2));

% Iliacus
Model.Informed.Lmt(16,1,1:n) = repmat(sum(Model.Informed.Lcst(16,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV176,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV225,[1,1,n]),Segment(5).Informed.Q)).^2));

% Psoas
Model.Informed.Lmt(17,1,1:n) = repmat(sum(Model.Informed.Lcst(17,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV186,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV235,[1,1,n]),Segment(5).Informed.Q)).^2));

% Quadratus femoris
Model.Informed.Lmt(18,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(18,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV196,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV245,[1,1,n]),Segment(5).Informed.Q)).^2));

% Gemelli
Model.Informed.Lmt(19,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(19,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV206,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV255,[1,1,n]),Segment(5).Informed.Q)).^2));

% Piriformis
Model.Informed.Lmt(20,1,1:n) = repmat(sum(Model.Informed.Lcst(20,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV216,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV265,[1,1,n]),Segment(5).Informed.Q)).^2));

% Tensor fascia latae
Model.Informed.Lmt(21,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(21,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV226,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV275,[1,1,n]),Segment(5).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV275,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV285,[1,1,n]),Segment(5).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV285,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV103,[1,1,n]),Segment(3).Informed.Q)).^2));

% Gracilis
Model.Informed.Lmt(22,1,1:n) = repmat(sum(Model.Informed.Lcst(22,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV236,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV113,[1,1,n]),Segment(3).Informed.Q)).^2));

% Sartorius
Model.Informed.Lmt(23,1,1:n) = repmat(sum(Model.Informed.Lcst(23,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV276,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV295,[1,1,n]),Segment(5).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV295,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV153,[1,1,n]),Segment(3).Informed.Q)).^2));

% Semimembranosus
Model.Informed.Lmt(24,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(24,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV246,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV123,[1,1,n]),Segment(3).Informed.Q)).^2));

% Semitendinosus
Model.Informed.Lmt(25,1,1:n) = repmat(sum(Model.Informed.Lcst(25,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV256,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV133,[1,1,n]),Segment(3).Informed.Q)).^2));

% Biceps femoris long head
Model.Informed.Lmt(26,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(26,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV266,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV143,[1,1,n]),Segment(3).Informed.Q)).^2));

% Biceps femoris short head
Model.Informed.Lmt(27,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(27,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV305,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV163,[1,1,n]),Segment(3).Informed.Q)).^2));

% Rectus femoris
Model.Informed.Lmt(28,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(28,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV286,[1,1,n]),Segment(6).Informed.Q) - ...
    Mprod_array3(repmat(NV24,[1,1,n]),Segment(4).Informed.Q)).^2));
% ind = find(FE3 < -83.65);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(28,1,ind) = ... % repmat(sum(Model.Informed.Lcst(28,:)),[1,1,ni]) is null
%         sqrt(sum((Mprod_array3(repmat(NV286,[1,1,ni]),Segment(6).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV315,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV315,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV24,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))).^2));
% end

% Vastus medialis
Model.Informed.Lmt(29,1,1:n) = repmat(sum(Model.Informed.Lcst(29,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV325,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV34,[1,1,n]),Segment(4).Informed.Q)).^2));
% ind = find(FE3 <= -69.36 & FE3 > -101.99);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(29,1,ind) = repmat(sum(Model.Informed.Lcst(29,:)),[1,1,ni]) + ...
%         sqrt(sum((Mprod_array3(repmat(NV325,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))).^2));
% end
% ind = find(FE3 <= -101.99);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(29,1,ind) = repmat(sum(Model.Informed.Lcst(29,:)),[1,1,ni]) + ...
%         sqrt(sum((Mprod_array3(repmat(NV325,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV335,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV345,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV345,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV34,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))).^2));
% end

% Vastus intermedialis
Model.Informed.Lmt(30,1,1:n) = repmat(sum(Model.Informed.Lcst(30,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV355,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV44,[1,1,n]),Segment(4).Informed.Q)).^2));
% ind = find(FE3 <= -81.36);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(30,1,ind) = repmat(sum(Model.Informed.Lcst(30,:)),[1,1,ni]) + ...
%         sqrt(sum((Mprod_array3(repmat(NV355,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV365,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV365,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV44,[1,1,n]),Segment(4).Informed.Q(:,:,ind))).^2));
% end

% Vastus lateralis
Model.Informed.Lmt(31,1,1:n) = repmat(sum(Model.Informed.Lcst(31,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV375,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV54,[1,1,n]),Segment(4).Informed.Q)).^2));
% ind = find(FE3 <= -69.36 & FE3 > -110.06);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(31,1,ind) = repmat(sum(Model.Informed.Lcst(31,:)),[1,1,ni]) + ...
%         sqrt(sum((Mprod_array3(repmat(NV375,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV385,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV385,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))).^2));
% end
% ind = find(FE3 <= -110.06);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(31,1,ind) = repmat(sum(Model.Informed.Lcst(31,:)),[1,1,ni]) + ...
%         sqrt(sum((Mprod_array3(repmat(NV375,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV375,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV385,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV395,[1,1,ni]),Segment(5).Informed.Q(:,:,ind))).^2)) + ...
%         sqrt(sum((Mprod_array3(repmat(NV395,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%         Mprod_array3(repmat(NV54,[1,1,ni]),Segment(4).Informed.Q(:,:,ind))).^2));
% end

% Gastrocnemius medialis
Model.Informed.Lmt(32,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(32,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV415,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV405,[1,1,n]),Segment(5).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV405,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV173,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV42,[1,1,n]),Segment(2).Informed.Q)).^2));
% ind = find(FE3 < -44.14);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(32,1,ind) = ... % repmat(sum(Model.Informed.Lcst(32,:)),[1,1,ni]) is null
%     sqrt(sum((Mprod_array3(repmat(NV405,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%     Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind))).^2)) + ...
%     sqrt(sum((Mprod_array3(repmat(NV173,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%     Mprod_array3(repmat(NV42,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))).^2));
% end

% Gastrocnemius lateralis
Model.Informed.Lmt(33,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(33,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV435,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV425,[1,1,n]),Segment(5).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV425,[1,1,n]),Segment(5).Informed.Q) - ...
    Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q)).^2)) + ...
    sqrt(sum((Mprod_array3(repmat(NV183,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV52,[1,1,n]),Segment(2).Informed.Q)).^2));
% ind = find(FE3 < -44.14);
% if ~isempty(ind)
%     ni = size(ind,1);
%     Model.Informed.Lmt(33,1,ind) = ... % repmat(sum(Model.Informed.Lcst(32,:)),[1,1,ni]) is null
%     sqrt(sum((Mprod_array3(repmat(NV425,[1,1,ni]),Segment(5).Informed.Q(:,:,ind)) - ...
%     Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind))).^2)) + ...
%     sqrt(sum((Mprod_array3(repmat(NV183,[1,1,ni]),Segment(3).Informed.Q(:,:,ind)) - ...
%     Mprod_array3(repmat(NV52,[1,1,ni]),Segment(2).Informed.Q(:,:,ind))).^2));
% end

% Soleus
Model.Informed.Lmt(34,1,1:n) = ... % repmat(sum(Model.Informed.Lcst(34,:)),[1,1,n]) is null
    sqrt(sum((Mprod_array3(repmat(NV193,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV62,[1,1,n]),Segment(2).Informed.Q)).^2));

% Tibialis posterior
Model.Informed.Lmt(35,1,1:n) = repmat(sum(Model.Informed.Lcst(35,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV203,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV72,[1,1,n]),Segment(2).Informed.Q)).^2));

% Tibialis anterior
Model.Informed.Lmt(36,1,1:n) = repmat(sum(Model.Informed.Lcst(36,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV283,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV92,[1,1,n]),Segment(2).Informed.Q)).^2));

% Peroneus brevis
Model.Informed.Lmt(37,1,1:n) = repmat(sum(Model.Informed.Lcst(37,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV223,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV92,[1,1,n]),Segment(2).Informed.Q)).^2));

% Peroneus longus
Model.Informed.Lmt(38,1,1:n) = repmat(sum(Model.Informed.Lcst(38,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV233,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV102,[1,1,n]),Segment(2).Informed.Q)).^2));

% Peroneus tertius
Model.Informed.Lmt(39,1,1:n) = repmat(sum(Model.Informed.Lcst(39,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV243,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV112,[1,1,n]),Segment(2).Informed.Q)).^2));

% Extensor digitorum longus
Model.Informed.Lmt(40,1,1:n) = repmat(sum(Model.Informed.Lcst(40,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV253,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV122,[1,1,n]),Segment(2).Informed.Q)).^2));

% Extensor hallucis longus
Model.Informed.Lmt(41,1,1:n) = repmat(sum(Model.Informed.Lcst(41,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV263,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV132,[1,1,n]),Segment(2).Informed.Q)).^2));

% Flexor digitorum longus
Model.Informed.Lmt(42,1,1:n) = repmat(sum(Model.Informed.Lcst(42,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV273,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV142,[1,1,n]),Segment(2).Informed.Q)).^2));

% Flexor hallucis longus
Model.Informed.Lmt(43,1,1:n) = repmat(sum(Model.Informed.Lcst(43,:)),[1,1,n]) + ...
    sqrt(sum((Mprod_array3(repmat(NV283,[1,1,n]),Segment(3).Informed.Q) - ...
    Mprod_array3(repmat(NV152,[1,1,n]),Segment(2).Informed.Q)).^2));



