function Contribution = computeContributions(Segment,Joint,Model,weight)

% Number of frames
n = size(Segment(2).rM,3);

% -------------------------------------------------------------------------
% Introduction of 3D forces
% -------------------------------------------------------------------------

% Prepare variables
% -------------------------------------------------------------------------
% Segment parameters
u1 = Segment(1).Q(1:3,1,:);
rP1 = Segment(1).Q(4:6,1,:);
rD1 = Segment(1).Q(7:9,1,:);
w1 = Segment(1).Q(10:12,1,:);

u2 = Segment(2).Q(1:3,1,:);
rP2 = Segment(2).Q(4:6,1,:);
rD2 = Segment(2).Q(7:9,1,:);
w2 = Segment(2).Q(10:12,1,:);

u3 = Segment(3).Q(1:3,1,:);
rP3 = Segment(3).Q(4:6,1,:);
rD3 = Segment(3).Q(7:9,1,:);
w3 = Segment(3).Q(10:12,1,:);

u4 = Segment(4).Q(1:3,1,:);
rP4 = Segment(4).Q(4:6,1,:);
rD4 = Segment(4).Q(7:9,1,:);
w4 = Segment(4).Q(10:12,1,:);

u5 = Segment(5).Q(1:3,1,:);
rP5 = Segment(5).Q(4:6,1,:);
rD5 = Segment(5).Q(7:9,1,:);
w5 = Segment(5).Q(10:12,1,:);

% Center of mass rCi
temp = Mprod_array3(Q2Tuw_array3(Segment(2).Q),...
    repmat([Segment(2).rCs;1],[1 1 n]));
rC2 = temp(1:3,:,:);
temp = Mprod_array3(Q2Tuw_array3(Segment(3).Q),...
    repmat([Segment(3).rCs;1],[1 1 n]));
rC3 = temp(1:3,:,:);
temp = Mprod_array3(Q2Tuw_array3(Segment(4).Q),...
    repmat([Segment(4).rCs;1],[1 1 n]));
rC4 = temp(1:3,:,:);
temp = Mprod_array3(Q2Tuw_array3(Segment(5).Q),...
    repmat([Segment(5).rCs;1],[1 1 n]));
rC5 = temp(1:3,:,:);

% Transpose of the interpolation matrix of rPi
NPit = [zeros(3,3,n);...
    repmat(eye(3,3),[1,1,n]);...
    zeros(3,3,n);...
    zeros(3,3,n)];

% Composition of interpolation matrices and lever arms
M33_2(1:3,2,:) = rP2-rD2;
M33_2(4:6,3,:) = -w2;
M33_2(7:9,3,:) = w2;
M33_2(10:12,1,:) = u2;

M33_3(1:3,2,:) = rP3-rD3;
M33_3(4:6,3,:) = -w3;
M33_3(7:9,3,:) = w3;
M33_3(10:12,1,:) = u3;

M33_4(1:3,2,:) = rP4-rD4;
M33_4(4:6,3,:) = -w4;
M33_4(7:9,3,:) = w4;
M33_4(10:12,1,:) = u4;

M33_5(1:3,2,:) = rP5-rD5;
M33_5(4:6,3,:) = -w5;
M33_5(7:9,3,:) = w5;
M33_5(10:12,1,:) = u5;

% Bstar
Bstar1(1:3,1,:) = cross(w1,u1);
Bstar1(1:3,2,:) = cross(u1,(rP1-rD1));
Bstar1(1:3,3,:) = cross(-(rP1-rD1),w1);

Bstar2(1:3,1,:) = cross(w2,u2);
Bstar2(1:3,2,:) = cross(u2,(rP2-rD2));
Bstar2(1:3,3,:) = cross(-(rP2-rD2),w2);

Bstar3(1:3,1,:) = cross(w3,u3);
Bstar3(1:3,2,:) = cross(u3,(rP3-rD3));
Bstar3(1:3,3,:) = cross(-(rP3-rD3),w3);

Bstar4(1:3,1,:) = cross(w4,u4);
Bstar4(1:3,2,:) = cross(u4,(rP4-rD4));
Bstar4(1:3,3,:) = cross(-(rP4-rD4),w4);

Bstar5(1:3,1,:) = cross(w5,u5);
Bstar5(1:3,2,:) = cross(u5,(rP5-rD5));
Bstar5(1:3,3,:) = cross(-(rP5-rD5),w5);

% Nstar2t (pseudo interpolation matrix)
Nstar2t = Mprod_array3(M33_2,Minv_array3(Bstar2));
Nstar3t = Mprod_array3(M33_3,Minv_array3(Bstar3));
Nstar4t = Mprod_array3(M33_4,Minv_array3(Bstar4));
Nstar5t = Mprod_array3(M33_5,Minv_array3(Bstar5));

% Transformation of ground reaction wrench {F0R 
% at center of pressure rP1                {M0R
% -------------------------------------------------------------------------
% Initialisation
Model.LR = zeros(48,6,n);

% LR
Model.LR(1:12,1:6,:) = [NPit + ...
    Mprod_array3(Nstar2t,Vskew_array3(rP1-rP2)), ...
    Mprod_array3(Nstar2t,Bstar1)];

% Transformation of dynamic wrenches {FiG 
% at center of mass rci              {MiG
% -------------------------------------------------------------------------
% Initialisation
Model.LG = zeros(48,24,n);

% LR
Model.LG(1:12,1:6,:) = [NPit + ...
    Mprod_array3(Nstar2t,Vskew_array3(rC2-rP2)), ...
    Mprod_array3(Nstar2t,Bstar2)];
Model.LG(13:24,7:12,:) = [NPit + ...
    Mprod_array3(Nstar3t,Vskew_array3(rC3-rP3)), ...
    Mprod_array3(Nstar3t,Bstar3)];
Model.LG(25:36,13:18,:) = [NPit + ...
    Mprod_array3(Nstar4t,Vskew_array3(rC4-rP4)), ...
    Mprod_array3(Nstar4t,Bstar4)];
Model.LG(37:48,19:24,:) = [NPit + ...
    Mprod_array3(Nstar5t,Vskew_array3(rC5-rP5)), ...
    Mprod_array3(Nstar5t,Bstar5)];

clear temp Contribution
for i = 1:size(Model.Lever,2)    
    A = [-Mprod_array3(Mtran_array3(Model.ZK),Model.LR) ...
        Mprod_array3(Mtran_array3(Model.ZK),Model.LG)];
    b = Mprod_array3(Mtran_array3(Model.ZK),Mprod_array3(Model.Lever(:,i,:),Model.X(i,:,:)));
    
    w = 1e-2;
    Q0 = repmat(eye(30),[1,1,n]);
    Q0(1,1,:) = repmat(w,[1,1,n]);
    Q0(2,2,:) = repmat(w,[1,1,n]);
    Q0(3,3,:) = repmat(w,[1,1,n]);
    Q0(4,4,:) = repmat(w,[1,1,n]);
    Q0(5,5,:) = repmat(w,[1,1,n]);
    
    Astar = Mprod_array3(A,Minv_array3(Q0));
    temp(:,i,:) = Mprod_array3(Mprod_array3(Minv_array3(Q0),Mpinv_array3(Astar)),b);
    
    Contribution.muscleForce.F1R(:,i,:) = temp(1:3,i,:);
    Contribution.muscleForce.M1R(:,i,:) = Mprod_array3(Bstar1,temp(4:6,i,:));    
    Contribution.muscleForce.d2Qdt2(:,i,:) = Mprod_array3(...
        Mpinv_array3(Model.G),Mprod_array3(Model.LG,temp(7:30,i,:)));
end
% Sum
Contribution.muscleForce.sumF0R = sum(temp(1:3,:,:),2);                 
Contribution.muscleForce.sumM0R = sum(temp(4:6,:,:),2);
% Residual
Contribution.muscleForce.resFOR = -Joint(1).F - sum(temp(1:3,:,:),2);
Contribution.muscleForce.resMOR = -Joint(1).M - sum(temp(4:6,:,:),2);

% Vertical GRF
GMAX = Contribution.muscleForce.F1R(2,1,:) + ...
    Contribution.muscleForce.F1R(2,2,:) + ...
    Contribution.muscleForce.F1R(2,3,:);

GMED = Contribution.muscleForce.F1R(2,4,:) + ...
    Contribution.muscleForce.F1R(2,5,:) + ...
    Contribution.muscleForce.F1R(2,6,:);

HAM = Contribution.muscleForce.F1R(2,24,:) + ...
    Contribution.muscleForce.F1R(2,25,:) + ...
    Contribution.muscleForce.F1R(2,26,:);

RF = Contribution.muscleForce.F1R(2,28,:);

VAS = Contribution.muscleForce.F1R(2,29,:) + ...
    Contribution.muscleForce.F1R(2,30,:) + ...
    Contribution.muscleForce.F1R(2,31,:);

GAS = Contribution.muscleForce.F1R(2,32,:) + ...
    Contribution.muscleForce.F1R(2,33,:);

SOL = Contribution.muscleForce.F1R(2,34,:);

SUM = sum(Contribution.muscleForce.F1R(2,:,:),2);
SUM_noPF = sum(Contribution.muscleForce.F1R(2,[1:31,36,39:41],:),2);
SUM_PF = sum(Contribution.muscleForce.F1R(2,[32:35,37:38,42:43],:),2);

figure; hold on;
area(squeeze(interpft(-Joint(1).F(2,:,:),101))'/(9.81*weight),'FaceColor',[0.8,0.8,0.8],'EdgeColor','none');
plot(squeeze(interpft(GMAX(:,:,:),101))'/(9.81*weight),'color',[0,0,1],'linewidth',2);
plot(squeeze(interpft(GMED(:,:,:),101))'/(9.81*weight),'color',[0.7,0,1],'linewidth',2);
plot(squeeze(interpft(HAM(:,:,:),101))'/(9.81*weight),'color','magenta','linewidth',2);
plot(squeeze(interpft(RF(:,:,:),101))'/(9.81*weight),'color',[1,0,0],'linewidth',2);
plot(squeeze(interpft(VAS(:,:,:),101))'/(9.81*weight),'color',[1,0.5,0],'linewidth',2);
plot(squeeze(interpft(GAS(:,:,:),101))'/(9.81*weight),'color',[0,1,0],'linewidth',2);
plot(squeeze(interpft(SOL(:,:,:),101))'/(9.81*weight),'color',[0,1,0.7],'linewidth',2);
plot(squeeze(interpft(SUM(:,:,:),101))'/(9.81*weight),'color',[0,0,0],'linewidth',2,'linestyle','-');
legend({'Vertical GRF','GMAX','GMED','HAM','RF','VAS','GAS','SOL','SUM'});

% Fore-aft GRF
GMAX = Contribution.muscleForce.F1R(1,1,:) + ...
    Contribution.muscleForce.F1R(1,2,:) + ...
    Contribution.muscleForce.F1R(1,3,:);

GMED = Contribution.muscleForce.F1R(1,4,:) + ...
    Contribution.muscleForce.F1R(1,5,:) + ...
    Contribution.muscleForce.F1R(1,6,:);

HAM = Contribution.muscleForce.F1R(1,24,:) + ...
    Contribution.muscleForce.F1R(1,25,:) + ...
    Contribution.muscleForce.F1R(1,26,:);

RF = Contribution.muscleForce.F1R(1,28,:);

VAS = Contribution.muscleForce.F1R(1,29,:) + ...
    Contribution.muscleForce.F1R(1,30,:) + ...
    Contribution.muscleForce.F1R(1,31,:);

GAS = Contribution.muscleForce.F1R(1,32,:) + ...
    Contribution.muscleForce.F1R(1,33,:);

SOL = Contribution.muscleForce.F1R(1,34,:);

SUM = sum(Contribution.muscleForce.F1R(1,:,:),2);
SUM_noPF = sum(Contribution.muscleForce.F1R(1,[1:31,36,39:41],:),2);
SUM_PF = sum(Contribution.muscleForce.F1R(1,[32:35,37:38,42:43],:),2);

figure; hold on;
area(squeeze(interpft(-Joint(1).F(1,:,:),101))'/(9.81*weight),'FaceColor',[0.8,0.8,0.8],'EdgeColor','none');
plot(squeeze(interpft(GMAX(:,:,:),101))'/(9.81*weight),'color',[0,0,1],'linewidth',2);
plot(squeeze(interpft(GMED(:,:,:),101))'/(9.81*weight),'color',[0.7,0,1],'linewidth',2);
plot(squeeze(interpft(HAM(:,:,:),101))'/(9.81*weight),'color','magenta','linewidth',2);
plot(squeeze(interpft(RF(:,:,:),101))'/(9.81*weight),'color',[1,0,0],'linewidth',2);
plot(squeeze(interpft(VAS(:,:,:),101))'/(9.81*weight),'color',[1,0.5,0],'linewidth',2);
plot(squeeze(interpft(GAS(:,:,:),101))'/(9.81*weight),'color',[0,1,0],'linewidth',2);
plot(squeeze(interpft(SOL(:,:,:),101))'/(9.81*weight),'color',[0,1,0.7],'linewidth',2);
plot(squeeze(interpft(SUM(:,:,:),101))'/(9.81*weight),'color',[0,0,0],'linewidth',2,'linestyle','-');
legend({'Fore-aft GRF','GMAX','GMED','HAM','RF','VAS','GAS','SOL','SUM'});

% Mediolateral GRF
GMAX = Contribution.muscleForce.F1R(3,1,:) + ...
    Contribution.muscleForce.F1R(3,2,:) + ...
    Contribution.muscleForce.F1R(3,3,:);

GMED = Contribution.muscleForce.F1R(3,4,:) + ...
    Contribution.muscleForce.F1R(3,5,:) + ...
    Contribution.muscleForce.F1R(3,6,:);

HAM = Contribution.muscleForce.F1R(3,24,:) + ...
    Contribution.muscleForce.F1R(3,25,:) + ...
    Contribution.muscleForce.F1R(3,26,:);

RF = Contribution.muscleForce.F1R(3,28,:);

VAS = Contribution.muscleForce.F1R(3,29,:) + ...
    Contribution.muscleForce.F1R(3,30,:) + ...
    Contribution.muscleForce.F1R(3,31,:);

GAS = Contribution.muscleForce.F1R(3,32,:) + ...
    Contribution.muscleForce.F1R(3,33,:);

SOL = Contribution.muscleForce.F1R(3,34,:);

SUM = sum(Contribution.muscleForce.F1R(3,:,:),2);
SUM_noPF = sum(Contribution.muscleForce.F1R(3,[1:31,36,39:41],:),2);
SUM_PF = sum(Contribution.muscleForce.F1R(3,[32:35,37:38,42:43],:),2);

figure; hold on;
area(squeeze(interpft(-Joint(1).F(3,:,:),101))'/(9.81*weight),'FaceColor',[0.8,0.8,0.8],'EdgeColor','none');
plot(squeeze(interpft(GMAX(:,:,:),101))'/(9.81*weight),'color',[0,0,1],'linewidth',2);
plot(squeeze(interpft(GMED(:,:,:),101))'/(9.81*weight),'color',[0.7,0,1],'linewidth',2);
plot(squeeze(interpft(HAM(:,:,:),101))'/(9.81*weight),'color','magenta','linewidth',2);
plot(squeeze(interpft(RF(:,:,:),101))'/(9.81*weight),'color',[1,0,0],'linewidth',2);
plot(squeeze(interpft(VAS(:,:,:),101))'/(9.81*weight),'color',[1,0.5,0],'linewidth',2);
plot(squeeze(interpft(GAS(:,:,:),101))'/(9.81*weight),'color',[0,1,0],'linewidth',2);
plot(squeeze(interpft(SOL(:,:,:),101))'/(9.81*weight),'color',[0,1,0.7],'linewidth',2);
plot(squeeze(interpft(SUM(:,:,:),101))'/(9.81*weight),'color',[0,0,0],'linewidth',2,'linestyle','-');
legend({'Mediolateral GRF','GMAX','GMED','HAM','RF','VAS','GAS','SOL','SUM'});

%%
% % Individual muscle force contributions to angular accelerations
% % -------------------------------------------------------------------------
% 
% % Contribution of musculo-tendon forces on angular and linear accelerations
% % Segment(2)
% T = Q2Tuv_array3(Segment(2).Q);
% for i = 1:43
%     temp = [Contribution.muscleForce.d2Qdt2(1:3,i,:), ...
%         Contribution.muscleForce.d2Qdt2(4:6,i,:)- ...
%         Contribution.muscleForce.d2Qdt2(7:9,i,:), ...
%         Contribution.muscleForce.d2Qdt2(10:12,i,:)];
%     d2Tdt2 = [Mprod_array3(temp,Minv_array3(repmat(Segment(2).B,[1,1,n]))), ...
%         Contribution.muscleForce.d2Qdt2(4:6,i,:)];
%     H = Mprod_array3(d2Tdt2,Minv_array3(T));
%     G = H(1:3,1:3,:);
%     temp2 = 0.5*(G-Mtran_array3(G));
%     angleacc = [-temp2(2,3,:); temp2(1,3,:);-temp2(1,2,:)]; % unskew the vector of angles
%     linacc = H(:,4,:);
%     
%     Contribution.muscleForce.alpha2(:,i,:) = angleacc;
%     Contribution.muscleForce.a2(:,i,:) = linacc;
% end
% 
% % Contribution of musculo-tendon forces on angular and linear accelerations
% % Segment(3)
% T = Q2Tuv_array3(Segment(3).Q);
% for i = 1:43
%     temp = [Contribution.muscleForce.d2Qdt2(13:15,i,:), ...
%         Contribution.muscleForce.d2Qdt2(16:18,i,:)- ...
%         Contribution.muscleForce.d2Qdt2(19:21,i,:), ...
%         Contribution.muscleForce.d2Qdt2(22:24,i,:)];
%     d2Tdt2 = [Mprod_array3(temp,Minv_array3(repmat(Segment(3).B,[1,1,n]))), ...
%         Contribution.muscleForce.d2Qdt2(4:6,i,:)];
%     H = Mprod_array3(d2Tdt2,Minv_array3(T));
%     G = H(1:3,1:3,:);
%     temp2 = 0.5*(G-Mtran_array3(G));
%     angleacc = [-temp2(2,3,:); temp2(1,3,:);-temp2(1,2,:)]; % unskew the vector of angles
%     linacc = H(:,4,:);
%     
%     Contribution.muscleForce.alpha3(:,i,:) = angleacc;
%     Contribution.muscleForce.a3(:,i,:) = linacc;
% end
% 
% % Contribution of musculo-tendon forces on angular and linear accelerations
% % Segment(4)
% T = Q2Tuv_array3(Segment(4).Q);
% for i = 1:43
%     temp = [Contribution.muscleForce.d2Qdt2(25:27,i,:), ...
%         Contribution.muscleForce.d2Qdt2(28:30,i,:)- ...
%         Contribution.muscleForce.d2Qdt2(31:33,i,:), ...
%         Contribution.muscleForce.d2Qdt2(34:36,i,:)];
%     d2Tdt2 = [Mprod_array3(temp,Minv_array3(repmat(Segment(4).B,[1,1,n]))), ...
%         Contribution.muscleForce.d2Qdt2(4:6,i,:)];
%     H = Mprod_array3(d2Tdt2,Minv_array3(T));
%     G = H(1:3,1:3,:);
%     temp2 = 0.5*(G-Mtran_array3(G));
%     angleacc = [-temp2(2,3,:); temp2(1,3,:);-temp2(1,2,:)]; % unskew the vector of angles
%     linacc = H(:,4,:);
%     
%     Contribution.muscleForce.alpha4(:,i,:) = angleacc;
%     Contribution.muscleForce.a4(:,i,:) = linacc;
% end
% 
% % Contribution of musculo-tendon forces on angular and linear accelerations
% % Segment(5)
% T = Q2Tuv_array3(Segment(5).Q);
% for i = 1:43
%     temp = [Contribution.muscleForce.d2Qdt2(37:39,i,:), ...
%         Contribution.muscleForce.d2Qdt2(40:42,i,:)- ...
%         Contribution.muscleForce.d2Qdt2(43:45,i,:), ...
%         Contribution.muscleForce.d2Qdt2(46:48,i,:)];
%     d2Tdt2 = [Mprod_array3(temp,Minv_array3(repmat(Segment(5).B,[1,1,n]))), ...
%         Contribution.muscleForce.d2Qdt2(4:6,i,:)];
%     H = Mprod_array3(d2Tdt2,Minv_array3(T));
%     G = H(1:3,1:3,:);
%     temp2 = 0.5*(G-Mtran_array3(G));
%     angleacc = [-temp2(2,3,:); temp2(1,3,:);-temp2(1,2,:)]; % unskew the vector of angles
%     linacc = H(:,4,:);
%     
%     Contribution.muscleForce.alpha5(:,i,:) = angleacc;
%     Contribution.muscleForce.a5(:,i,:) = linacc;
% end
% 
% figure; hold on;
% for i = 1:43
%     plot(squeeze(Contribution.muscleForce.alpha2(3,i,:)*180/pi)');
% end
% 
% figure; hold on;
% for i = 1:43
%     plot(squeeze(Contribution.muscleForce.alpha3(3,i,:)*180/pi)');
% end
% 
% figure; hold on;
% for i = 1:43
%     plot(squeeze(Contribution.muscleForce.alpha4(3,i,:)*180/pi)');
% end
% 
% figure; hold on;
% for i = 1:43
%     plot(squeeze(Contribution.muscleForce.alpha5(3,i,:)*180/pi)');
% end

%%
% Individual muscle force contributions to joint contact, ligament and bone
% forces
% -------------------------------------------------------------------------
for i = 1:size(Model.Lever,2)
    Contribution.muscleForce.lambda1(:,i,:) = ...
        Mprod_array3(...
            Mpinv_array3(Mprod_array3(Mtran_array3(Model.ZK2),Mtran_array3(Model.K1))),...
            -Mprod_array3(Mtran_array3(Model.ZK2),Mprod_array3(Model.G,Contribution.muscleForce.d2Qdt2(:,i,:)))...
                +Mprod_array3(Mtran_array3(Model.ZK2),...
                    [Mprod_array3(NPit,Contribution.muscleForce.F1R(:,i,:))+...
                    Mprod_array3(Nstar2t,(Contribution.muscleForce.M1R(:,i,:)+cross((rP1-rP2),Contribution.muscleForce.F1R(:,i,:))));...
                    zeros(36,1,n)])...
            +Mprod_array3(Mtran_array3(Model.ZK2),Mprod_array3(Model.Lever(:,i,:),Model.X(i,:,:)))...
        );    
end

%%
% Contribution to TBmed
iK1 = 6;

VAS = Contribution.muscleForce.lambda1(iK1,29,:) + ...
    Contribution.muscleForce.lambda1(iK1,30,:) + ...
    Contribution.muscleForce.lambda1(iK1,31,:);

GMAX = Contribution.muscleForce.lambda1(iK1,1,:) + ...
    Contribution.muscleForce.lambda1(iK1,2,:) + ...
    Contribution.muscleForce.lambda1(iK1,3,:);

SOL = Contribution.muscleForce.lambda1(iK1,34,:);

GAS = Contribution.muscleForce.lambda1(iK1,32,:) + ...
    Contribution.muscleForce.lambda1(iK1,33,:);

HAM = Contribution.muscleForce.lambda1(iK1,24,:) + ...
    Contribution.muscleForce.lambda1(iK1,25,:) + ...
    Contribution.muscleForce.lambda1(iK1,26,:);

RF = Contribution.muscleForce.lambda1(iK1,28,:);

BFsh = Contribution.muscleForce.lambda1(iK1,27,:);

SUM = sum(Contribution.muscleForce.lambda1(iK1,:,:),2);

% Sritharan 2012
figure;
hold on;
% plot(squeeze(Model.X(43+iK1,:,:))'/(9.81*weight),'black');
area(squeeze(SUM)'/(9.81*weight),'facecolor',[0.6 0.6 0.6],'linewidth',2);
plot(squeeze(GAS)'/(9.81*weight),'color','blue','linewidth',2);
plot(squeeze(BFsh)'/(9.81*weight),'color','green','linewidth',2);
plot(squeeze(VAS)'/(9.81*weight),'color','red','linewidth',2);
plot(squeeze(RF)'/(9.81*weight),'color','cyan','linewidth',2);
plot(squeeze(HAM)'/(9.81*weight),'color','magenta','linewidth',2);

% Contribution to TBlat
iK1 = 7;

VAS = Contribution.muscleForce.lambda1(iK1,29,:) + ...
    Contribution.muscleForce.lambda1(iK1,30,:) + ...
    Contribution.muscleForce.lambda1(iK1,31,:);

GMAX = Contribution.muscleForce.lambda1(iK1,1,:) + ...
    Contribution.muscleForce.lambda1(iK1,2,:) + ...
    Contribution.muscleForce.lambda1(iK1,3,:);

SOL = Contribution.muscleForce.lambda1(iK1,34,:);

GAS = Contribution.muscleForce.lambda1(iK1,32,:) + ...
    Contribution.muscleForce.lambda1(iK1,33,:);

HAM = Contribution.muscleForce.lambda1(iK1,24,:) + ...
    Contribution.muscleForce.lambda1(iK1,25,:) + ...
    Contribution.muscleForce.lambda1(iK1,26,:);

RF = Contribution.muscleForce.lambda1(iK1,28,:);

BFsh = Contribution.muscleForce.lambda1(iK1,27,:);

SUM = sum(Contribution.muscleForce.lambda1(iK1,:,:),2);

% Sritharan 2012
figure;
hold on;
% plot(squeeze(Model.X(43+iK1,:,:))'/(9.81*weight),'black');
area(squeeze(SUM)'/(9.81*weight),'facecolor',[0.6 0.6 0.6],'linewidth',2);
plot(squeeze(GAS)'/(9.81*weight),'color','blue','linewidth',2);
plot(squeeze(BFsh)'/(9.81*weight),'color','green','linewidth',2);
plot(squeeze(VAS)'/(9.81*weight),'color','red','linewidth',2);
plot(squeeze(RF)'/(9.81*weight),'color','cyan','linewidth',2);
plot(squeeze(HAM)'/(9.81*weight),'color','magenta','linewidth',2);

% Contribution to TBtot
iK1 = 6;
iK2 = 7;

VAS = Contribution.muscleForce.lambda1(iK1,29,:) + ...
    Contribution.muscleForce.lambda1(iK1,30,:) + ...
    Contribution.muscleForce.lambda1(iK1,31,:) + ...
    Contribution.muscleForce.lambda1(iK2,29,:) + ...
    Contribution.muscleForce.lambda1(iK2,30,:) + ...
    Contribution.muscleForce.lambda1(iK2,31,:);

GMAX = Contribution.muscleForce.lambda1(iK1,1,:) + ...
    Contribution.muscleForce.lambda1(iK1,2,:) + ...
    Contribution.muscleForce.lambda1(iK1,3,:) + ...
    Contribution.muscleForce.lambda1(iK2,1,:) + ...
    Contribution.muscleForce.lambda1(iK2,2,:) + ...
    Contribution.muscleForce.lambda1(iK2,3,:);

SOL = Contribution.muscleForce.lambda1(iK1,34,:) + ...
    Contribution.muscleForce.lambda1(iK2,34,:);

GAS = Contribution.muscleForce.lambda1(iK1,32,:) + ...
    Contribution.muscleForce.lambda1(iK1,33,:) + ...
    Contribution.muscleForce.lambda1(iK2,32,:) + ...
    Contribution.muscleForce.lambda1(iK2,33,:);

HAM = Contribution.muscleForce.lambda1(iK1,24,:) + ...
    Contribution.muscleForce.lambda1(iK1,25,:) + ...
    Contribution.muscleForce.lambda1(iK1,26,:) + ...
    Contribution.muscleForce.lambda1(iK2,24,:) + ...
    Contribution.muscleForce.lambda1(iK2,25,:) + ...
    Contribution.muscleForce.lambda1(iK2,26,:);

RF = Contribution.muscleForce.lambda1(iK1,28,:) + ...
    Contribution.muscleForce.lambda1(iK2,28,:);

BFsh = Contribution.muscleForce.lambda1(iK1,27,:) + ...
    Contribution.muscleForce.lambda1(iK2,27,:);

SUM = sum(Contribution.muscleForce.lambda1(iK1,:,:),2)+sum(Contribution.muscleForce.lambda1(iK2,:,:),2);

% Sritharan 2012
figure;
hold on;
% plot(squeeze(Model.X(43+iK1,:,:)+Model.X(43+iK2,:,:))'/(9.81*weight),'black');
area(squeeze(SUM)'/(9.81*weight),'facecolor',[0.6 0.6 0.6],'linewidth',2);
plot(squeeze(GAS)'/(9.81*weight),'color','blue','linewidth',2);
plot(squeeze(BFsh)'/(9.81*weight),'color','green','linewidth',2);
plot(squeeze(VAS)'/(9.81*weight),'color','red','linewidth',2);
plot(squeeze(RF)'/(9.81*weight),'color','cyan','linewidth',2);
plot(squeeze(HAM)'/(9.81*weight),'color','magenta','linewidth',2);

%%
% Contribution to any K1 lambda => axial compression femur
% figure; hold on;
% k = 1:n;
% k0 = linspace(1,n,101);
% 
% plot(interp1(k,permute(Model.X(43+19,:,:),[3,1,2]),k0)/(9.81*weight),'black');
% plot(ones(size(-1:3))*65,-1:3,'--b');
% 
% % for i = 1:43
% %     plot(squeeze(Contribution.muscleForce.lambda1(19,i,:))'/(9.81*weight),'black')
% % end
% 
% GMAX = Contribution.muscleForce.lambda1(19,1,:) + ...
%     Contribution.muscleForce.lambda1(19,2,:) + ...
%     Contribution.muscleForce.lambda1(19,3,:);
% 
% GMED = Contribution.muscleForce.lambda1(19,4,:) + ...
%     Contribution.muscleForce.lambda1(19,5,:) + ...
%     Contribution.muscleForce.lambda1(19,6,:);
% 
% GMIN = Contribution.muscleForce.lambda1(19,7,:) + ...
%     Contribution.muscleForce.lambda1(19,8,:) + ...
%     Contribution.muscleForce.lambda1(19,9,:);
% 
% ADD = Contribution.muscleForce.lambda1(19,10,:) + ...
%     Contribution.muscleForce.lambda1(19,11,:) + ...
%     Contribution.muscleForce.lambda1(19,12,:) + ...
%     Contribution.muscleForce.lambda1(19,13,:) + ...
%     Contribution.muscleForce.lambda1(19,14,:);
% 
% ILIAC = Contribution.muscleForce.lambda1(19,16,:);
% 
% PSOAS = Contribution.muscleForce.lambda1(19,17,:);
% 
% TFL = Contribution.muscleForce.lambda1(19,21,:);
% 
% GRA = Contribution.muscleForce.lambda1(19,22,:);
% 
% SAR = Contribution.muscleForce.lambda1(19,23,:);
% 
% HAM = Contribution.muscleForce.lambda1(19,24,:) + ...
%     Contribution.muscleForce.lambda1(19,25,:) + ...
%     Contribution.muscleForce.lambda1(19,26,:);
% 
% BFsh = Contribution.muscleForce.lambda1(19,27,:);
% 
% RF = Contribution.muscleForce.lambda1(19,28,:);
% 
% VAS = Contribution.muscleForce.lambda1(19,29,:) + ...
%     Contribution.muscleForce.lambda1(19,30,:) + ...
%     Contribution.muscleForce.lambda1(19,31,:);
% 
% plot(interp1(k,permute(GMAX,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(GMED,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(GMIN,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(ADD,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(ILIAC,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(PSOAS,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(TFL,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(GRA,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(SAR,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(HAM,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(BFsh,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(RF,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% plot(interp1(k,permute(VAS,[3,1,2]),k0)/(9.81*weight),'color','blue','linewidth',2);
% 
% legend({'Total','Glutei maximus', 'Glutei medius', ...
%     'Glutei minimus', 'Adductors', ...
%     'Illiacus', 'Psoas', ...
%     'Tensor fasciae latae', ...
%     'Gracilis', 'Sartorius', 'Hamstrings', ...
%     'Biceps femoris short head', 'Rectus femoris', ...
%     'Vastii'})
%%
% Contribution to any K1 lambda => axial compression tibia
% figure; hold on;
% 
% plot(squeeze(Model.X(43+18,:,:))'/(9.81*weight),'black');
% 
% for i = 1:43
%     plot(squeeze(Contribution.muscleForce.lambda1(18,i,:))'/(9.81*weight),'black')
% end
% 
% legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
%     'Gluteus maximus III', 'Gluteus medius I', ...
%     'Gluteus medius II', 'Gluteus medius III', ...
%     'Gluteus minimus I', 'Gluteus minimus II', ...
%     'Gluteus minimus III', 'Adductor longus', ...
%     'Adductor brevis', 'Adductor magnus I', ...
%     'Adductor magnus II', 'Adductor magnus III', ...
%     'Pectineus', 'Illiacus', 'Psoas', ...
%     'Quadratus femoris', 'Gemelli', ...
%     'Piriformis','Tensor fasciae latae', ...
%     'Gracilis', 'Sartorius', 'Semimembranosus', ...
%     'Semitendinus', 'Biceps femoris long head', ...
%     'Biceps femoris short head', 'Rectus femoris', ...
%     'Vastus medialis', ...
%     'Vastus intermedialis', 'Vastus lateralis', ...
%     'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
%     'Soleus', 'Tibialis posterior', ...
%     'Tibialis anterior', 'Peroneus brevis', ...
%     'Peroneus longus', 'Peroneus tertius', ...
%     'Extensor digitorum longus', 'Extensor hallucis longus', ...
%     'Flexor digitorum longus', 'Flexor hallucis longus'})
% %%
% Contribution to any K1 lambda => ACL
figure; hold on;

plot(squeeze(Model.X(43+8,:,:))'/(9.81*weight),'black');

for i = 1:43
    plot(squeeze(Contribution.muscleForce.lambda1(8,i,:))'/(9.81*weight),'black')
end

legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
    'Gluteus maximus III', 'Gluteus medius I', ...
    'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', ...
    'Gluteus minimus III', 'Adductor longus', ...
    'Adductor brevis', 'Adductor magnus I', ...
    'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', ...
    'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', ...
    'Tibialis anterior', 'Peroneus brevis', ...
    'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
%%
% Contribution to any K1 lambda => PCL
figure; hold on;

plot(squeeze(Model.X(43+9,:,:))'/(9.81*weight),'black');

for i = 1:43
    plot(squeeze(Contribution.muscleForce.lambda1(9,i,:))'/(9.81*weight),'black')
end

plot(squeeze(Contribution.muscleForce.lambda1(9,i,:))'/(9.81*weight),'black')

legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
    'Gluteus maximus III', 'Gluteus medius I', ...
    'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', ...
    'Gluteus minimus III', 'Adductor longus', ...
    'Adductor brevis', 'Adductor magnus I', ...
    'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', ...
    'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', ...
    'Tibialis anterior', 'Peroneus brevis', ...
    'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
%%
% Contribution to any K1 lambda => PF X-axis contact
figure; hold on;

plot(squeeze(Model.X(43+11,:,:))'/(9.81*weight),'black');

for i = 1:43
    plot(squeeze(Contribution.muscleForce.lambda1(11,i,:))'/(9.81*weight),'black')
end

QUAD = Contribution.muscleForce.lambda1(11,28,:) + ...
    Contribution.muscleForce.lambda1(11,29,:) + ...
    Contribution.muscleForce.lambda1(11,30,:) + ...
    Contribution.muscleForce.lambda1(11,31,:);
plot(squeeze(QUAD)'/(9.81*weight),'red')

legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
    'Gluteus maximus III', 'Gluteus medius I', ...
    'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', ...
    'Gluteus minimus III', 'Adductor longus', ...
    'Adductor brevis', 'Adductor magnus I', ...
    'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', ...
    'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', ...
    'Tibialis anterior', 'Peroneus brevis', ...
    'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
%%
% Contribution to any K1 lambda => PF Y-axis contact
figure; hold on;

plot(squeeze(Model.X(43+12,:,:))'/(9.81*weight),'black');

for i = 1:43
    plot(squeeze(Contribution.muscleForce.lambda1(12,i,:))'/(9.81*weight),'black')
end

legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
    'Gluteus maximus III', 'Gluteus medius I', ...
    'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', ...
    'Gluteus minimus III', 'Adductor longus', ...
    'Adductor brevis', 'Adductor magnus I', ...
    'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', ...
    'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', ...
    'Tibialis anterior', 'Peroneus brevis', ...
    'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
%%
% Contribution to any K1 lambda => PF Z-axis contact
figure; hold on;

plot(squeeze(Model.X(43+13,:,:))'/(9.81*weight),'black');

for i = 1:43
    plot(squeeze(Contribution.muscleForce.lambda1(13,i,:))'/(9.81*weight),'black')
end

legend({'Total','Gluteus maximus I', 'Gluteus maximus II', ...
    'Gluteus maximus III', 'Gluteus medius I', ...
    'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', ...
    'Gluteus minimus III', 'Adductor longus', ...
    'Adductor brevis', 'Adductor magnus I', ...
    'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', ...
    'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', ...
    'Tibialis anterior', 'Peroneus brevis', ...
    'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})