% ?????????????????????????????????????????????????????????????????????????
% To be finalise

function Segment = Define_Scale(Segment,Model)


% Mean segment geometry 
for i = [2,3,5,6] % From i = 2 (Foot) to i = 6 (Pelvis)
    
    Segment(i).Informed.L = mean(sqrt(sum((Segment(i).Informed.Q(4:6,1,:) - ...
            Segment(i).Informed.Q(7:9,1,:)).^2)),3);  % Mean segment length
    
    % Alpha angle between (rP - rD) and w
    Segment(i).Informed.alpha = mean(acosd(dot(Segment(i).Informed.Q(4:6,1,:) - ...
        Segment(i).Informed.Q(7:9,1,:), Segment(i).Informed.Q(10:12,1,:))./...
        sqrt(sum((Segment(i).Informed.Q(4:6,1,:) - ...
        Segment(i).Informed.Q(7:9,1,:)).^2))),3);
    
    % Beta angle between u and w
    Segment(i).Informed.beta = mean(acosd(dot(Segment(i).Informed.Q(10:12,1,:), ...
        Segment(i).Informed.Q(1:3,1,:))),3);
    
    % Gamma angle between u and (rP - rD)
    Segment(i).Informed.gamma = mean(acosd(dot(Segment(i).Informed.Q(1:3,1,:), ...
        Segment(i).Informed.Q(4:6,1,:) - Segment(i).Informed.Q(7:9,1,:))./...
        sqrt(sum((Segment(i).Informed.Q(4:6,1,:) - ...
        Segment(i).Informed.Q(7:9,1,:)).^2))),3);
    
    % Matrix B from SCS to NSCS
    Segment(i).Informed.B = [1, ...
        Segment(i).Informed.L*cosd(Segment(i).Informed.gamma), ...
        cosd(Segment(i).Informed.beta); ...
        0, ...
        Segment(i).Informed.L*sind(Segment(i).Informed.gamma), ...
        (cosd(Segment(i).Informed.alpha) - ...
        cosd(Segment(i).Informed.beta)*cosd(Segment(i).Informed.gamma))/ ...
        sind(Segment(i).Informed.gamma); ...
        0, ...
        0, ...
        sqrt(1 - cosd(Segment(i).Informed.beta)^2 - ...
        ((cosd(Segment(i).Informed.alpha) - ...
        cosd(Segment(i).Informed.beta)*cosd(Segment(i).Informed.gamma))/ ...
        sind(Segment(i).Informed.gamma))^2)];

end


% % Scale
% Segment(2).Informed.Scale = Model.Informed.Height/Model.Generic.Height;
% Segment(3).Informed.Scale = Model.Informed.Height/Model.Generic.Height;
% Segment(4).Informed.Scale = Model.Informed.Height/Model.Generic.Height;
% Segment(5).Informed.Scale = Model.Informed.Height/Model.Generic.Height;
% Segment(6).Informed.Scale = Model.Informed.Height/Model.Generic.Height;
%
Segment(2).Informed.Scale = Segment(3).Informed.L/Segment(3).Generic.L;
Segment(3).Informed.Scale = Segment(3).Informed.L/Segment(3).Generic.L;
Segment(4).Informed.Scale = (Segment(3).Informed.L/Segment(3).Generic.L + ...
    Segment(5).Informed.L/Segment(5).Generic.L)/2;
Segment(5).Informed.Scale = Segment(5).Informed.L/Segment(5).Generic.L;
Segment(6).Informed.Scale = Segment(5).Informed.L/Segment(5).Generic.L;

