% F2a

% fc = 5; % Cut frequency for filtering

% Activation
for j = 1:43
    
%     % Muscle length
%     Model.Lm(j,1,1:n) = Mprod_array3((Model.Lmt(j,1,:) - Model.Lts(j)), ...
%         repmat(cos(Model.pennation(j))^(-1),[1,1,n]));
%     
%     % Normalised muscle velocity
%     Model.V(j,1,1:n) = Mprod_array3(Vfilt_array3(...
%         Derive_array3(Model.Lm(j,:,:),1/f),f,fc), ...
%         repmat(cos(Model.pennation(j)),[1,1,n]))./...
%         repmat(Model.V0max(j),[1,1,n]);
    
    % Force-length
    Fla(j,1,1:n) = ones(1,1,n) - ...
        ((Model.Lm(j,1,:) - repmat(Model.L0(j),[1,1,n]))./...
        (0.56*repmat(Model.L0(j),[1,1,n]))).^2;
    
    % Force-velocity
    Fv(j,1,1:n) = ones(1,1,n) - tanh(0.3*Model.V(j,:,:));
    
    % Passive
    Flp(j,1,1:n) = exp(repmat(10,[1,1,n]).* ...
        (Model.Lm(j,1,:)./repmat(Model.L0(j),[1,1,n]) ... % Normalised
        - ones(1,1,n))).*repmat(1/exp(5),[1,1,n]);

    % From musculo-tendon force to activation
    % Fm = Fmax*cos(pennation) * (Fa(l)*F(v) * a + Fp(l))
    %  a = Fm/[Fa(l)*F(v)*Fmax*cos(pennation)] - Fp(l)/[Fa(l)*F(v)]
    % a = A*Fm + B
    A(j,j,1:n) = (repmat(61*Model.PCSA(j,1)*cos(Model.pennation(j,1)),[1,1,n]).*...
        Fla(j,1,1:n).*Fv(j,1,1:n)).^-1;
    B(j,1,1:n) = - Flp(j,1,1:n)./(Fla(j,1,1:n).*Fv(j,1,1:n));
    
    % Maximal musculo-tendon force at activation = 1
    Fmax(j,1,1:n) = repmat(61*Model.PCSA(j,1)*cos(Model.pennation(j,1)),[1,1,n]).*...
        (Fla(j,1,1:n).*Fv(j,1,1:n).*ones(1,1,n) + Flp(j,1,1:n));


end

% a = Fm/[Fa(l)*F(v)*Fmax*cos(pennation)] - Fp(l)/[Fa(l)*F(v)]
% a = A*Fm + B
Model.a = Mprod_array3(A,Model.Fm) + B;

% Normalised length
figure
subplot(1,2,1)
plot(squeeze(Model.Lm./repmat(Model.L0,[1,1,n]))');
legend({'Gluteus maximus I', 'Gluteus maximus II', 'Gluteus maximus III', ...
    'Gluteus medius I', 'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', 'Gluteus minimus III', ...
    'Adductor longus', 'Adductor brevis', ...
    'Adductor magnus I', 'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', 'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', 'Tibialis anterior', ...
    'Peroneus brevis', 'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
% Normalised velocity
subplot(1,2,2)
plot(squeeze(Model.V)');
legend({'Gluteus maximus I', 'Gluteus maximus II', 'Gluteus maximus III', ...
    'Gluteus medius I', 'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', 'Gluteus minimus III', ...
    'Adductor longus', 'Adductor brevis', ...
    'Adductor magnus I', 'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', 'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', 'Tibialis anterior', ...
    'Peroneus brevis', 'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})


% Activation
figure
plot(squeeze(Model.a)');
legend({'Gluteus maximus I', 'Gluteus maximus II', 'Gluteus maximus III', ...
    'Gluteus medius I', 'Gluteus medius II', 'Gluteus medius III', ...
    'Gluteus minimus I', 'Gluteus minimus II', 'Gluteus minimus III', ...
    'Adductor longus', 'Adductor brevis', ...
    'Adductor magnus I', 'Adductor magnus II', 'Adductor magnus III', ...
    'Pectineus', 'Illiacus', 'Psoas', ...
    'Quadratus femoris', 'Gemelli', ...
    'Piriformis','Tensor fasciae latae', ...
    'Gracilis', 'Sartorius', 'Semimembranosus', ...
    'Semitendinus', 'Biceps femoris long head', ...
    'Biceps femoris short head', 'Rectus femoris', ...
    'Vastus medialis', 'Vastus intermedialis', 'Vastus lateralis', ...
    'Gastrocnemius medialis', 'Gastrocnemius lateralis', ...
    'Soleus', 'Tibialis posterior', 'Tibialis anterior', ...
    'Peroneus brevis', 'Peroneus longus', 'Peroneus tertius', ...
    'Extensor digitorum longus', 'Extensor hallucis longus', ...
    'Flexor digitorum longus', 'Flexor hallucis longus'})
